version: '3.9'

services:
  cache:
    image: redis
  twitchbot:
    build:
      context: ./
      dockerfile: ./services/twitchbot/Dockerfile
    depends_on:
      - cache

    environment:
      - TWITCH_TOKEN=oauth:q7pfo9bbuofc0j3pcinlu8guke2seg
      - TWITCH_USER=xnugget_
      - TWITCH_CHANNEL=xnugget_